import {
  TbBrandTypescript,
  TbBrandJavascript,
  TbBrandPhp,
  TbBrandPython,
  TbBrandCSharp,
  TbBrandReact,
  TbBrandAngular,
  TbBrandNextjs,
  TbBrandReactNative,
  TbBrandFigma,
  TbBrandDjango,
  TbBrandNodejs,
  TbBrandMongodb,
  TbSql,
  TbBrandGraphql,
  TbBrandDocker,
  TbBrandGoogleAnalytics,
  TbBrandWordpress,
  TbBrandGithub,
  TbBrandGit,
  TbBrandNpm,
} from "react-icons/tb";
import { BiLogoJava, BiLineChart, BiScatterChart } from "react-icons/bi";
import {
  SiPytorch,
  SiTensorflow,
  SiKeras,
  SiAdobeillustrator,
  SiAndroidstudio,
  SiExpress,
  SiFlask,
  SiAdobexd,
  SiCanva,
  SiNumpy,
  SiPandas,
  SiScikitlearn,
  SiJsonwebtokens,
  SiOpencv,
  SiYolo,
  SiLinux,
  SiBootstrap,
  SiVite,
  SiSequelize,
  SiHtml5,
  SiCss3,
} from "react-icons/si";
const tools = [
  {
    txt: "Javascript",
    bgColor: "#F0DB4F",
    logo: <TbBrandJavascript />,
    txtColor: "#323330",
    type: "languages",
  },
  {
    txt: "Typescript",
    bgColor: "#007acc",
    logo: <TbBrandTypescript />,
    txtColor: "#fff",
    type: "languages",
  },
  {
    txt: "Python",
    bgColor: "#ffde57",
    logo: <TbBrandPython />,
    txtColor: "#4584B6",
    type: "languages",
  },
  {
    txt: "Java",
    bgColor: "#0c89c6",
    logo: <BiLogoJava />,
    txtColor: "#eb2024",
    type: "languages",
  },
  {
    txt: "PHP",
    bgColor: "#AEB2D5",
    logo: <TbBrandPhp />,
    txtColor: "#000000",
    type: "languages",
  },
  {
    txt: "C#",
    bgColor: "#684D95",
    logo: <TbBrandCSharp />,
    txtColor: "#E4DCF0",
    type: "languages",
  },
  {
    txt: "React",
    bgColor: "#61DBFB",
    logo: <TbBrandReact />,
    txtColor: "#1c2d4c",
    type: "frontend",
  },
  {
    txt: "React Native",
    bgColor: "#61DBFB",
    logo: <TbBrandReactNative />,
    txtColor: "#1c2d4c",
    type: "frontend",
  },
  {
    txt: "Angular",
    bgColor: "#c3002f",
    logo: <TbBrandAngular />,
    txtColor: "#eaeaeaa",
    type: "frontend",
  },
  {
    txt: "NextJS",
    bgColor: "#fff",
    logo: <TbBrandNextjs />,
    txtColor: "#000",
    type: "frontend",
  },
  {
    txt: "CSS frameworks",
    bgColor: "#264de4",
    logo: <SiCss3 />,
    txtColor: "#ffffff",
    type: "frontend",
  },
  {
    txt: "WordPress",
    bgColor: "#21759B",
    logo: <TbBrandWordpress />,
    txtColor: "#FFFFFF",
    type: "frontend",
  },
  {
    txt: "Tensorflow",
    bgColor: "#ff6f61",
    logo: <SiTensorflow />,
    txtColor: "#1c2d4c",
    type: "ml",
  },
  {
    txt: "Keras",
    bgColor: "#D00000",
    logo: <SiKeras />,
    txtColor: "#fff",
    type: "ml",
  },
  {
    txt: "PyTorch",
    bgColor: "#EE4C2C",
    logo: <SiPytorch />,
    txtColor: "#fff",
    type: "ml",
  },
  {
    txt: "Scikit-learn",
    bgColor: "#F7931E",
    logo: <SiScikitlearn />,
    txtColor: "#FFFFFF",
    type: "ml",
  },
  {
    txt: "Adobe Illustrator",
    bgColor: "#f8a829",
    logo: <SiAdobeillustrator />,
    txtColor: "#3c240c",
    type: "other",
  },
  {
    txt: "Figma",
    bgColor: "#1abcfe",
    logo: <TbBrandFigma />,
    txtColor: "#f24e1e",
    type: "other",
  },
  {
    txt: "Node.js",
    bgColor: "#68A063",
    logo: <TbBrandNodejs />,
    txtColor: "#303030",
    type: "backend",
  },
  {
    txt: "Express.js",
    bgColor: "#000000",
    logo: <SiExpress />,
    txtColor: "#ffffff",
    type: "backend",
  },
  {
    txt: "Flask",
    bgColor: "#fff",
    logo: <SiFlask />,
    txtColor: "#000",
    type: "backend",
  },
  {
    txt: "JWT",
    bgColor: "#01F3E7",
    logo: <SiJsonwebtokens />,
    txtColor: "#FB015B",
    type: "backend",
  },
  {
    txt: "SQL",
    bgColor: "#ff8800",
    logo: <TbSql />,
    txtColor: "#ffffff",
    type: "backend",
  },
  {
    txt: "MongoDB",
    bgColor: "#47A248",
    logo: <TbBrandMongodb />,
    txtColor: "#ffffff",
    type: "backend",
  },
  {
    txt: "NumPy",
    bgColor: "#4A90E2",
    logo: <SiNumpy />,
    txtColor: "#FFFFFF",
    type: "ml",
  },
  {
    txt: "Pandas",
    bgColor: "#150458",
    logo: <SiPandas />,
    txtColor: "#FFFFFF",
    type: "ml",
  },
  {
    txt: "Version control",
    bgColor: "#F34F29",
    logo: <TbBrandGit />,
    txtColor: "#FFFFFF",
    type: "other",
  },
  {
    txt: "Linux Terminal",
    bgColor: "#000000",
    logo: <SiLinux />,
    txtColor: "#FFFFFF",
    type: "other",
  },
  {
    txt: "Docker",
    bgColor: "#2496ED",
    logo: <TbBrandDocker />,
    txtColor: "#FFFFFF",
    type: "other",
  },
  {
    txt: "npm",
    bgColor: "#CB3837",
    logo: <TbBrandNpm />,
    txtColor: "#FFFFFF",
    type: "other",
  },
];

export default tools;
